### ISSUE TITLE
Have you see this before? Gem::InstallError: public_suffix requires Ruby version >= 2.0

### ISSUE THREAD

**Issue by chrismarksus** [weppos/publicsuffix-ruby#74] opened 2015-04-02 22:24 UTC
I have installed 2.0, 2.1.0 and 2.2.1 on a local machine and on the koding.com vm and I get this error every time. ```gem install public_suffix -v '1.5.0'``` also fails with the same error. I am assuming that there is something that I missed and not the gem. 

Do you have any ideas?

```
$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies......
Using RedCloth 4.2.9
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.5.1
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.1
Using addressable 2.3.8
Using blankslate 2.1.2.4
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.0
Using fast-stemmer 1.0.2
Using classifier-reborn 2.0.3
Using coffee-script-source 1.9.1
Using execjs 2.4.0
Using coffee-script 2.3.0
Using colorator 0.1
Using colored 1.2
Using rdoc 4.2.0
Using css_parser 1.2.6
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using deadweight 0.2.2
Using ffi 1.9.8
Using ethon 0.7.3
Using gemoji 2.1.0
Using net-dns 0.8.0
 
Gem::InstallError: public_suffix requires Ruby version >= 2.0.
An error occurred while installing public_suffix (1.5.0), and Bundler cannot continue.
Make sure that `gem install public_suffix -v '1.5.0'` succeeds before bundling.

$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
```
This is what is in my Gemfile

```
source 'https://rubygems.org'

gem 'github-pages'
gem 'html-proofer'
gem 'scss_lint_reporter_checkstyle'
gem 'scss-lint'
gem 'mdl'
gem 'deadweight'
```

**Comment by G33kDude** [comment] 2015-04-08 00:24
I'm having this issue as well

**Comment by weppos** [comment] 2015-04-08 10:45
What is the output of `gem env` from the same folder?

**Comment by weppos** [comment] 2015-04-10 12:04
Closing as I can't reproduce. Please provide the output as requested in order to help me debugging the issue.

**Closed by weppos** 2015-04-10 12:04 UTC

**Comment by G33kDude** [comment] 2015-04-10 12:20
My problem turned out to be that although I had ruby 2.2.1 installed, it was defaulting to ruby 1.9.3
